name: Deploy

on:
  push:
    branches:
      - source  # default branch

jobs:
  build:
    name: "deploy to github pages"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
      run: |
        npm install
        npm run deploy
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}